import 'dart:math' as math;

import 'package:control/control.dart';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:flutter_project/src/common/constant/config.dart';
import 'package:flutter_project/src/feature/authentication/widget/authentication_scope.dart';
import 'package:flutter_project/src/feature/call/controller/call_controller.dart';
import 'package:flutter_project/src/feature/call/models/call_type.dart';
import 'package:flutter_project/src/feature/call/widgets/call_config_widget.dart';

/// Generates a random Google-Meet-style meeting code, e.g. "abc-defg-hij".
String _generateMeetingCode() {
  const chars = 'abcdefghijklmnopqrstuvwxyz';
  final rng = math.Random();
  String part(int len) => List.generate(len, (_) => chars[rng.nextInt(chars.length)]).join();
  return '${part(3)}-${part(4)}-${part(3)}';
}

/// Lobby screen — create a new meeting or join one with a code.
class CallLobbyWidget extends StatefulWidget {
  const CallLobbyWidget({super.key});

  @override
  State<CallLobbyWidget> createState() => _CallLobbyWidgetState();
}

class _CallLobbyWidgetState extends State<CallLobbyWidget> {
  late final _scope = CallConfigInhWidget.of(context);
  late final _callController = _scope.callController;
  late final _callDataController = _scope.callDataController;
  late final TextEditingController _channelController;

  /// True when the current code in the field was generated by us (not typed).
  bool _isGenerated = false;

  @override
  void initState() {
    super.initState();
    _channelController = TextEditingController(text: _callDataController.lastChannelName);
  }

  @override
  void dispose() {
    _channelController.dispose();
    super.dispose();
  }

  void _newMeeting() {
    _channelController.text = _generateMeetingCode();
    setState(() => _isGenerated = true);
  }

  void _copyCode() {
    Clipboard.setData(ClipboardData(text: _channelController.text.trim()));
    ScaffoldMessenger.of(context).showSnackBar(
      const SnackBar(
        content: Text('Meeting code copied to clipboard'),
        duration: Duration(seconds: 2),
        behavior: SnackBarBehavior.floating,
      ),
    );
  }

  void _startCall(CallType callType) {
    final channelName = _channelController.text.trim();
    if (channelName.isEmpty) return;
    final user = AuthenticationScope.userOf(context);
    if (user == null) return;
    _callDataController.setLastChannelName(channelName);
    _callController.join(
      channelName: channelName,
      callType: callType,
      uid: user.id,
      token: Config.agoraTempToken.isEmpty ? null : Config.agoraTempToken,
    );
  }

  @override
  Widget build(BuildContext context) {
    final user = AuthenticationScope.userOf(context);
    final theme = Theme.of(context);
    return Scaffold(
      appBar: AppBar(
        title: Text('Hi, ${user?.name ?? 'Guest'}'),
        actions: [
          IconButton(
            icon: const Icon(Icons.logout),
            tooltip: 'Sign out',
            onPressed: () => AuthenticationScope.controllerOf(context).logout(),
          ),
        ],
      ),
      body: StateConsumer<CallController, CallState>(
        controller: _callController,
        builder: (context, state, _) => Center(
          child: ConstrainedBox(
            constraints: const BoxConstraints(maxWidth: 480),
            child: Padding(
              padding: const EdgeInsets.all(24),
              child: Column(
                mainAxisAlignment: MainAxisAlignment.center,
                crossAxisAlignment: CrossAxisAlignment.stretch,
                children: [
                  const Icon(Icons.video_call_rounded, size: 64, color: Colors.teal),
                  const SizedBox(height: 12),
                  Text(
                    'Agora Call',
                    textAlign: TextAlign.center,
                    style: theme.textTheme.headlineMedium?.copyWith(fontWeight: FontWeight.bold),
                  ),
                  const SizedBox(height: 32),

                  // ── New meeting button ──────────────────────────────────
                  FilledButton.icon(
                    onPressed: _newMeeting,
                    icon: const Icon(Icons.add_circle_outline),
                    label: const Text('New Meeting'),
                    style: FilledButton.styleFrom(
                      backgroundColor: Colors.teal,
                      padding: const EdgeInsets.symmetric(vertical: 16),
                    ),
                  ),

                  const SizedBox(height: 24),
                  Row(
                    children: [
                      const Expanded(child: Divider()),
                      Padding(
                        padding: const EdgeInsets.symmetric(horizontal: 12),
                        child: Text(
                          'or join with a code',
                          style: theme.textTheme.bodySmall?.copyWith(color: Colors.white38),
                        ),
                      ),
                      const Expanded(child: Divider()),
                    ],
                  ),
                  const SizedBox(height: 24),

                  // ── Channel / meeting code field ────────────────────────
                  TextField(
                    controller: _channelController,
                    textInputAction: TextInputAction.done,
                    onChanged: (_) {
                      if (_isGenerated) setState(() => _isGenerated = false);
                    },
                    decoration: InputDecoration(
                      labelText: 'Meeting Code',
                      hintText: 'e.g. abc-defg-hij',
                      prefixIcon: const Icon(Icons.meeting_room_outlined),
                      border: const OutlineInputBorder(),
                      // Copy button shown only after generating a code
                      suffixIcon: _isGenerated
                          ? IconButton(
                              icon: const Icon(Icons.copy, color: Colors.teal),
                              tooltip: 'Copy code',
                              onPressed: _copyCode,
                            )
                          : null,
                    ),
                  ),

                  // ── Generated-code share hint ───────────────────────────
                  if (_isGenerated) ...[const SizedBox(height: 10), _ShareHint(onCopy: _copyCode)],

                  if (state is Call$ErrorState) ...[
                    const SizedBox(height: 12),
                    _ErrorCard(message: state.message, onRetry: _callController.retryInit),
                  ],

                  const SizedBox(height: 24),

                  // ── Call type buttons ────────────────────────────────────
                  AnimatedBuilder(
                    animation: _channelController,
                    builder: (context, _) {
                      final hasChannel = _channelController.text.trim().isNotEmpty;
                      return Row(
                        children: [
                          Expanded(
                            child: OutlinedButton.icon(
                              onPressed: hasChannel ? () => _startCall(CallType.audio) : null,
                              icon: const Icon(Icons.call),
                              label: const Text('Audio'),
                              style: OutlinedButton.styleFrom(
                                padding: const EdgeInsets.symmetric(vertical: 16),
                                side: const BorderSide(color: Colors.teal),
                                foregroundColor: Colors.teal,
                              ),
                            ),
                          ),
                          const SizedBox(width: 16),
                          Expanded(
                            child: FilledButton.icon(
                              onPressed: hasChannel ? () => _startCall(CallType.video) : null,
                              icon: const Icon(Icons.videocam),
                              label: const Text('Video'),
                              style: FilledButton.styleFrom(
                                backgroundColor: Colors.teal,
                                padding: const EdgeInsets.symmetric(vertical: 16),
                              ),
                            ),
                          ),
                        ],
                      );
                    },
                  ),

                  if (Config.agoraAppId.isEmpty) ...[
                    const SizedBox(height: 24),
                    const _ConfigWarning(),
                  ],
                ],
              ),
            ),
          ),
        ),
      ),
    );
  }
}

// ── Sub-widgets ──────────────────────────────────────────────────────────────

class _ShareHint extends StatelessWidget {
  const _ShareHint({required this.onCopy});

  final VoidCallback onCopy;

  @override
  Widget build(BuildContext context) => Container(
    padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 10),
    decoration: BoxDecoration(
      color: Colors.teal.withValues(alpha: 0.1),
      borderRadius: BorderRadius.circular(8),
      border: Border.all(color: Colors.teal.withValues(alpha: 0.3)),
    ),
    child: Row(
      children: [
        const Icon(Icons.share, size: 16, color: Colors.teal),
        const SizedBox(width: 8),
        const Expanded(
          child: Text(
            'Share this code with people you want in the meeting.',
            style: TextStyle(color: Colors.teal, fontSize: 12),
          ),
        ),
        TextButton(
          onPressed: onCopy,
          style: TextButton.styleFrom(
            foregroundColor: Colors.teal,
            padding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
            minimumSize: Size.zero,
            tapTargetSize: MaterialTapTargetSize.shrinkWrap,
          ),
          child: const Text('Copy', style: TextStyle(fontSize: 12)),
        ),
      ],
    ),
  );
}

class _ErrorCard extends StatelessWidget {
  const _ErrorCard({required this.message, required this.onRetry});

  final String message;
  final VoidCallback onRetry;

  @override
  Widget build(BuildContext context) => Card(
    color: Colors.red.shade900.withValues(alpha: 0.4),
    child: Padding(
      padding: const EdgeInsets.all(12),
      child: Row(
        children: [
          const Icon(Icons.error_outline, color: Colors.redAccent),
          const SizedBox(width: 8),
          Expanded(
            child: Text(message, style: const TextStyle(color: Colors.redAccent)),
          ),
          TextButton(onPressed: onRetry, child: const Text('Retry')),
        ],
      ),
    ),
  );
}

class _ConfigWarning extends StatelessWidget {
  const _ConfigWarning();

  @override
  Widget build(BuildContext context) => Card(
    color: Colors.orange.shade900.withValues(alpha: 0.4),
    child: const Padding(
      padding: EdgeInsets.all(12),
      child: Row(
        children: [
          Icon(Icons.warning_amber_rounded, color: Colors.orange),
          SizedBox(width: 8),
          Expanded(
            child: Text(
              'Agora App ID not configured. '
              'Set AGORA_APP_ID in your config file.',
              style: TextStyle(color: Colors.orange),
            ),
          ),
        ],
      ),
    ),
  );
}
